//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_hospital_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class appbook_tab
    {
        public int booking_id { get; set; }
        public System.DateTime app_date { get; set; }
        public System.TimeSpan app_time { get; set; }
        public int doctor_id { get; set; }
        public int patient_id { get; set; }
    }
}
