//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_hospital_app
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HOSPITALEntities : DbContext
    {
        public HOSPITALEntities()
            : base("name=HOSPITALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<patient_tab> patient_tab { get; set; }
        public virtual DbSet<book_tab> book_tab { get; set; }
        public virtual DbSet<appbook_tab> appbook_tab { get; set; }
    
        public virtual int p_register(string pna, Nullable<int> ag, string sex, string add, Nullable<long> mob, string emai, string una, string pass)
        {
            var pnaParameter = pna != null ?
                new ObjectParameter("pna", pna) :
                new ObjectParameter("pna", typeof(string));
    
            var agParameter = ag.HasValue ?
                new ObjectParameter("ag", ag) :
                new ObjectParameter("ag", typeof(int));
    
            var sexParameter = sex != null ?
                new ObjectParameter("sex", sex) :
                new ObjectParameter("sex", typeof(string));
    
            var addParameter = add != null ?
                new ObjectParameter("add", add) :
                new ObjectParameter("add", typeof(string));
    
            var mobParameter = mob.HasValue ?
                new ObjectParameter("mob", mob) :
                new ObjectParameter("mob", typeof(long));
    
            var emaiParameter = emai != null ?
                new ObjectParameter("emai", emai) :
                new ObjectParameter("emai", typeof(string));
    
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_register", pnaParameter, agParameter, sexParameter, addParameter, mobParameter, emaiParameter, unaParameter, passParameter);
        }
    
        public virtual int sp_login(string una, string pas, ObjectParameter status)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pasParameter = pas != null ?
                new ObjectParameter("pas", pas) :
                new ObjectParameter("pas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_login", unaParameter, pasParameter, status);
        }
    
        public virtual int sp_appoiment(Nullable<System.DateTime> appd, Nullable<System.TimeSpan> appt, Nullable<int> docid, Nullable<int> patid)
        {
            var appdParameter = appd.HasValue ?
                new ObjectParameter("appd", appd) :
                new ObjectParameter("appd", typeof(System.DateTime));
    
            var apptParameter = appt.HasValue ?
                new ObjectParameter("appt", appt) :
                new ObjectParameter("appt", typeof(System.TimeSpan));
    
            var docidParameter = docid.HasValue ?
                new ObjectParameter("docid", docid) :
                new ObjectParameter("docid", typeof(int));
    
            var patidParameter = patid.HasValue ?
                new ObjectParameter("patid", patid) :
                new ObjectParameter("patid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_appoiment", appdParameter, apptParameter, docidParameter, patidParameter);
        }
    
        public virtual ObjectResult<sp_bookingdet_Result> sp_bookingdet(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_bookingdet_Result>("sp_bookingdet", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_idget(string uname)
        {
            var unameParameter = uname != null ?
                new ObjectParameter("uname", uname) :
                new ObjectParameter("uname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_idget", unameParameter);
        }
    
        public virtual ObjectResult<sp_idgeting_Result> sp_idgeting(string uname)
        {
            var unameParameter = uname != null ?
                new ObjectParameter("uname", uname) :
                new ObjectParameter("uname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_idgeting_Result>("sp_idgeting", unameParameter);
        }
    }
}
